name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: -- health-cmd="mysqladmin ping -h localhost" --health-interval=30s --health-timeout=10s --health-retries=5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Lint
        run: npm run lint
      
      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build
        
      - name: Build Docker image
        run: docker build -t progressive-overload .
    
