name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: marshall
          MYSQL_DATABASE: progressive_overload
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: myuser
          RABBITMQ_DEFAULT_PASS: mypassword
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Copy test env
        run: cp .env.test .env

      - name: Lint
        run: npm run lint

      - name: E2E Test via Docker Compose  << 기존 코드 
        run: docker compose -f docker-compose.e2e.yml up --build --exit-code-from e2e-test-runner

