name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Copy test env
        run: cp .env.test .env

      - name: Unit Test & Coverage
        run: npm run test:ci

      - name: Run E2E Containers & Tests
        run: docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit

      - name: Build Docker Image
        run: docker build -t progressive-overload .